name: fanout-builds
on:
  push:
    branches:
      - master

run-name: ${{ github.actor }}

jobs:
  get-changed-files:
    outputs:
      matrix: ${{ steps.get-files.outputs.all_modified_files }}
    steps:
    - name: Get changed files
      id: get-files
      uses: tj-actions/changed-files@v44.5.5
      with:
        matrix: true
        dir_names: true
    - name: print files
      id: print-files
      run: echo '${{ steps.get-files.outputs.all_modified_files }}'