name: fanout-builds
on:
  push:
    branches:
      - master

run-name: ${{ github.actor }}

jobs:
  get-changed-files:
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.get-files.outputs.all_modified_files }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Get changed files
        id: get-files
        uses: tj-actions/changed-files@v44.5.5
        with:
          matrix: true
          dir_names: true
      - name: print files
        id: print-files
        run: echo '${{ steps.get-files.outputs.all_modified_files }}'
  
  matrix-job:
    runs-on: ubuntu-latest
    needs: get-changed-files
    strategy:
      matrix:
        directories: ${{ fromJSON(needs.get-changed-files.outputs.matrix) }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Echo dirs
        run: |
          echo ${{ matrix.directories }}