on:
  push:
  pull_request:

jobs:
  call-build-passing-data:
    uses: CradleKing24/actions-testing/.github/workflows/build.yaml@master
    with:
      sleep-seconds: 10
    secrets:
      envPAT: inherit