on:
  push:
    branch:
      - release/*
  workflow_call:
    inputs:
      sleep-seconds:
        required: true
        type: string

jobs:
  call-build:
    uses: CradleKing24/actions-testing/.github/workflows/build.yaml@master
    with:
      sleep-seconds: ${{ inputs.sleep-seconds }}
  scan-build:
    runs-on: ubuntu-latest
    steps:
    - name: Echo test
      run: echo Test
      shell: bash
