on:
  push:
  
  workflow_call:
    inputs:
      sleep-seconds:
        required: true
        type: string
        default: '5'

jobs:
  call-build:
    uses: CradleKing24/actions-testing/.github/workflows/build.yaml@master
    with:
      sleep-seconds: ${{ inputs.sleep-seconds }}
  scan-build:
    runs-on: ubuntu-latest
    needs: call-build
    steps:
    - name: Echo test
      run: echo Test ${{ needs.call-build.outputs.world }}
      shell: bash
